In [55]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
a_3d = np.array([i for i in range(27)]).reshape(3,3,3)
print(a_3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [5]:
print(a_3d.axis(0))

AttributeError: 'numpy.ndarray' object has no attribute 'axis'

In [50]:
len1 = 600
len2 = 400
x = np.linspace(-2,1,len1)
y = np.linspace(-1.5,1.5,len2)
# print(x)
# print(y)
c = x.reshape(len1,-1)+1j*y.reshape(-1,len2)
# print(c.ndim)
# print(c)
print(type(c[0][0]))

<class 'numpy.complex128'>


In [69]:
z=c
for i in range(50):
    z= z**2 + c
    r = np.abs(z)<50.0

C:\Users\Raunak Seksaria\AppData\Local\Temp\ipykernel_49056\2072548047.py:3: RuntimeWarning: overflow encountered in square
  z= z**2 + c
C:\Users\Raunak Seksaria\AppData\Local\Temp\ipykernel_49056\2072548047.py:3: RuntimeWarning: invalid value encountered in square
  z= z**2 + c


In [85]:
print(r)

[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]


In [86]:
!conda install opencv2

Solving environment: ...working... unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: ...working... unsuccessful initial attempt using frozen solve. Retrying with flexible solve.



PackagesNotFoundError: The following packages are not available from current channels:

  - opencv2

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.




In [82]:
import cv2 as cv
# plt.imshow(r)
cv.imshow(r)
plt.title("MandelBrot Fractal")

ModuleNotFoundError: No module named 'cv2'

In [87]:
import scipy